services:
  - type: web
    name: dicee-battle-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        value: "false"
      - key: FROM_EMAIL
        value: "noreply@dicee-battle.onrender.com"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
    healthCheckPath: /health
    autoDeploy: true

# Removed:
# - `disk` section: Not allowed in Free tier
# - `headers`: Only supported for static sites (not dynamic Node apps)

# databases section (commented) is fine as-is
