services:
  # Web service for the dice game
  - type: web
    name: dicee-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      # SMTP configuration for password reset emails (set these in Render dashboard)
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        value: "false"
      - key: FROM_EMAIL
        value: "no-reply@example.com"
    # Health check endpoint
    healthCheckPath: /
    # Auto-deploy from main branch
    autoDeploy: true

databases:
  # SQLite database will be handled by the application
  # Note: For production, consider using Render's PostgreSQL service
  # - name: dicee-db
  #   databaseName: dicee_game
  #   user: dicee_user
  #   plan: free